language: node_js
node_js:
  - "6.9.1"
cache: yarn
sudo: required
services:
  - docker
before_install:
    - docker info
    - docker build --rm=false -t webgl-test-ci .
script:
    - npm run docker-run
